version: '3.8'

services:
  frontend:
    build: ./react-project/app
    ports:
      - "3000:80"

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
    volumes:
      - db-data:/usr/src/app/prisma
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  db-data:
