name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Deploys when changes are pushed to the main branch

permissions:
  contents: write # Required for writing to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: app
        run: npm install

      - name: Build App
        working-directory: app
        run: npm run build
        env:
          REACT_APP_MOCK_API: 'true'
          GENERATE_SOURCEMAP: false

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/build
          branch: gh-pages
